### ISSUE TITLE
Uncaught ReferenceError: module is not defined on loading angular-permission.js

### ISSUE THREAD

**Issue by albv** [Narzerus/angular-permission#249]
I'm trying to upgrade from 2.3 but get this error message. Same problem with angular-permission-ui.js

**Comment by albv** [comment]
Fix in 3.1.1 doesn't work for me either. Same error on the line
 
`var _module = module || {};`

I think this should be 

`var _module = typeof module !== 'undefined' ? module : {};`

**Comment by albv** [comment]
Also I think it's not good to pollute global scope with _module variable. Maybe we could use local var?

**Comment by jstroem** [comment]
@masterspambot @albv It should be `var module = module || {}`, its the only way this works, since if the variable `module` is not defined prior `var module = module || {}` will not give you a referenceError while `var _module = module || {}` will.
However the idea that pulling the variable declaration inside of the function scope is sound and a good idea.

**Comment by kaynz** [comment]
Using `var module = module || {}` leads to `Failed to instantiate module permission.ui`

**Comment by albv** [comment]
@jstroem @masterspambot  If I am not missing something, export could be as simple as

```
if (typeof module !== 'undefined' && module.exports) {
  module.exports = permission.name;
}
```
neither IIFE nor local var required.
