### ISSUE TITLE
Angular-permission breaks state transition options

### ISSUE THREAD

**Issue by OverZealous** [Narzerus/angular-permission#26]
Due to the fact that angular-permission completely stops and restarts every state transition, any options passed in (for example, via `ui-sref-opts`) are lost.

This means it's impossible to use angular-permission and do things like `location: 'replace'`, because the option is lost.

**Comment by abhinandankothari** [comment]
@Narzerus after using angular-permission in my application all the CREATE button on all forms(10 approx) have stopped working because soon as the resource is created reload: true is passed in state options as to reload and newly created resource is shown in list, Using following line:
$state.go($state.current, {}, {reload: true})

I have read the above comments and also posted on ui-router github issue and waiting for the solution.
For the meantime can you help me with a temporary/hacky solution ?

**Comment by Narzerus** [comment]
Since this issue depends on a problem with ui-router's `$stateChangeStart` I've created the following discussion. Please have a look at #51

**Comment by abhinandankothari** [comment]
@Narzerus  0.2.15 of Angular UI Router is released, when will you be releasing angular-permission to incorporate the changes ?

**Comment by Narzerus** [comment]
I will check the changelog and see what this implies before giving a
straight answer, but this should be updated soon, if anyone wants to send a
PR to speed things up I'll have a look

**Comment by asperling** [comment]
I rewritten the thing into my own module in a synchronous fashion and it works. That way you don't need to prevent the state transition in any case but those which aren't allowed. Is there any reason you used promises rather than the sync approach? I do like and use promises a lot but I don't see the need in this scenario)

**Comment by Narzerus** [comment]
Many people have roles which require a request to some backend

**Comment by ronanquillevere** [comment]
Hello,

I am facing exactly the same pb as @abhinandankothari and using ui-router 0.2.15, any improvements from here ?

**Comment by Narzerus** [comment]
@ronanquillevere sadly as mentioned in the thread, this has to do with an issue on ui-router's end so there's not much we can do about it for now.

**Comment by ronanquillevere** [comment]
I did not dive into the details of the pb but I though 0.2.15 might have fixed the pb, so I understand this is not case right ?

**Comment by Narzerus** [comment]
Actually I'm testing this right now, will respond in a moment

**Comment by asperling** [comment]
@Narzerus
I understand your point. But since ui-routers capabilities (it's not a bug in my opinion) do not support this kind of implementation, why not simply go sync? When ui-router is ready then an async version could be released depending on that version of ui-router and up. 

As I see it one could more easily implement a workaround for the need of making requests during permission check (by caching those e.g.) as to find a way to cope with the issue of this thread. At least I guess a lot more people have said issue than the need to check back with a backend.

**Comment by Narzerus** [comment]
@asperling I'm not sure that's really the case, many people here need to query their back-end at specific points to get the actual session state, I cannot change such core behavior it would break everyone's code. I'm sorry if this is not the answer you were expecting, I'll try to find some way for this to work in your use-case

**Comment by ronanquillevere** [comment]
@Narzerus @asperling I do not have a strong opinion on the matter but I think making an asynch call to retrieve your permissions each time a route is called is not the best options in terms of performance. I personnaly do it only once when starting my app. 

Would be interesting if someone could share his use case for an asynch call

**Comment by Narzerus** [comment]
I agree with that, still it would depend on the use-case. Caching will still work swiftly with promises, which is why I'm using it, its the best for both cases (If it weren't for this issue we are having)

**Comment by Narzerus** [comment]
Welp, about the "I'm testing this" it was actually meant as a response for a different issue.

**Comment by ronanquillevere** [comment]
@asperling would you have a FORK with a sync version to share ?

**Comment by asperling** [comment]
@Narzerus I solved my case by integrating your great idea and some of your work in my own access module in a sync fashion and...
@ronanquillevere that's the reason why I have nothing to show for, at least no fork with a sync version.

But the main idea was to only stop propagation if a synchronous authorization check fails:

```
    $rootScope.$on('$stateChangeStart',
      function (event, toState, toParams, fromState, fromParams) {
        if (toState.$$finishAuthorize || !toState.data || !toState.data.permissions) {
          return;
        }
        var permissions = toState.data.permissions;
        if (permissions) {
          if (!AccessControl.authorizeSync(permissions, toParams)) {
            event.preventDefault();
            // If not authorized, redirect to wherever the route has defined, if defined at all
            var redirectTo = permissions.redirectTo;
            if (redirectTo) {
              $log.debug('ACCESS to %s DENIED, redirecting to %s', toState.name, redirectTo);
              $state.go(redirectTo, toParams);
            }
          }
        }
      }
    );
```  

See https://github.com/Narzerus/angular-permission/blob/v0.1.7/src/permission.mdl.js for comparision.

Then you'll need to refactor all promise based functions into synchronous ones. As an example:

```
      authorizeSync: function (rightMap, toParams) {

        AccessControl._validateRightMap(rightMap);
        var authorizing;

        if (rightMap.only) {
          authorizing = AccessControl._findMatchingRightSync(rightMap.only, toParams);
        } else {
          authorizing = !AccessControl._findMatchingRightSync(rightMap.except, toParams);
        }

        return authorizing;
      }
```
instead of https://github.com/Narzerus/angular-permission/blob/master/src/permission.svc.js#L128

(*my module is called **AccessControl**, you will need to change that)

Maybe I can manage to build such a synchronous fork some time...


And @Narzerus, you're right, just switch back to sync would affect all of those that have already implemented it. Not to easy...
