### ISSUE TITLE
Check permission in custom place

### ISSUE THREAD

**Issue by Blaze34** [Narzerus/angular-permission#28]
I need show link with ui-sref="resource.create" only if I have permission.

There is any way to do it?

**Comment by mark-veenstra** [comment]
Maybe it is an idea to write a custom directive that allows you to add attributes to elements where you can configure if the element should show or not, something like:

```html
<button type="button" permission-only="CanEditUser, Admin">Save User</button>
<button type="button" permission-except="anonymous">Save User</button>
```

For a reference look at this solution: http://jonsamwell.com/url-route-authorization-and-security-in-angular/#securing_ui_elements

**Comment by Narzerus** [comment]
I agree, it would be good to have both kinds of directives. Also it will be important to give some though about how the permissions should be evaluated so that it doesn't happen that each directive validates the same permissions again and again.

Imagine a role which validates through a back-end request, if we had 10 elements which use this directive it would mean 10 back-end calls. So clearly we must do some caching of the role validations, which might or might not be something tricky

**Comment by blowsie** [comment]
Are `authorize` and `canGoToState` still valid methods? Im struggling to find a way to use angular-permissions from within my controller or service.

I looked in the documentation but did not find any examples.

---

Question asked here:
http://stackoverflow.com/questions/42511785/angular-permission-testing-a-user-has-a-role-or-permission-from-a-controller
