### ISSUE TITLE
permission object takes first value in array 

### ISSUE THREAD

**Issue by gowram** [Narzerus/angular-permission#56]
Hi, 

I have problem with permission only array...
```
data: {
        permissions: {
          only: ['user', 'admin',]
         }
        }
```

it takes into consideration of first value only "user", just ignores second value "admin",
if i swap ["admin", "user"], it uses only "admin" not "user"..

is it right way to define?

**Comment by Narzerus** [comment]
Can you post your role definitions?

**Comment by gowram** [comment]
```
                if(result.userrole){
                    Permission.defineRole(result.userrole.name, function () {
                           return true;
                    });
                    console.log("Role defined as : "+ result.userrole.name );
                }else{

                     Permission.defineRole('anonymous', function () {
                        return true;
                    });
                  console.log("Roles and permissions not defined yet! Sign-in first...");

                }

```

I fetching roles from back end node services, its defining properly.

**Comment by Narzerus** [comment]
Both roles should be defined, you should instead return true/false if the
roles is true for the current session or not.

**Comment by gowram** [comment]
all my roles are dynamic, it get changed as per requirement.
right now i have 3 roles but going forward i might have 'n' number of roles.
please let me know what would be the appropriate way to achieve such dynamic role creation.

**Comment by Narzerus** [comment]
Another user at some point had a similar issue, the problem lies as you say, in the way you handle roles. Dynamic roles are not supported by Permission :/

I still think the might be away to work in the way you need to. But a rule must be followed:
Roles should be always defined, they should either return `true` or `false` depending on wether the current session has them.

For example you can create a provider called `CurrentRoles` or `CurrentPermissions` (depending on your authorization structure). And this provider could simply provide an array of string which represent active roles.

You would then need to create roles for each possible role in your system and have them return `true` / `false` depending on wether certain string is present on the array provided by the provider mentioned before.

Hope this helps, I'm closing this issue as this is Permission's expected behavior, if you wish to make a feature request please post it in the issues section and I will gladly read your proposal.

Cheers!
